import ctypes

class Vec2(ctypes.Structure):
    x: ctypes.c_float
    y: ctypes.c_float

    def __add__(self, other) -> "Vec2": ...
    def __sub__(self, other) -> "Vec2": ...
    def __mul__(self, scalar) -> "Vec2": ...
    def __rmul__(self, scalar) -> "Vec2": ...
    def normalize(self) -> "Vec2": ...
    def rotate(self, angle_deg: float) -> "Vec2": ...
    def dot(self, other: "Vec2") -> float: ...
    def norm_sq(self) -> float: ...
    def norm(self) -> float: ...
    def theta(self) -> float: ...
    def dist(self, other: "Vec2") -> float: ...
    def dist_sq(self, other: "Vec2") -> float: ...
